name: Hello World
version: "1.0.0"
slug: hello-world
description: A simple hello world demo app to test the repository setup
url: https://hub.docker.com/_/hello-world
image: docker.io/library/hello-world
arch:
- aarch64
- amd64
startup: once
boot: manual
